# Generated by Django 6.0.3 on 2026-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_category_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
