# Generated by Django 6.0.3 on 2026-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
